### ISSUE TITLE
Can't run timetra.diary executable

### ISSUE THREAD

**Issue by hyiltiz** [neithere/timetra.diary#5]
I am in OSX with Homebrew.  I installed with cloning the master c21f46dfab3b415fa1f1a2a3c4530177c9ab3342, then did a `python3 setup.py build` and `python3 setup.py build`. I installed all the modules while the `timetra.diary` tried to import when called as well as all the modules necessary to run the `./tests/*.py` files. 

This is what I get when I tried to run the program:
```BASH
$ timetra-diary
Traceback (most recent call last):
  File "/usr/local/bin/timetra-diary", line 10, in <module>
    load_entry_point('timetra.diary==0.2.0', 'console_scripts', 'timetra-diary')()
  File "/usr/local/lib/python3.5/site-packages/timetra.diary-0.2.0-py3.5.egg/timetra/diary/app.py", line 61, in main
    storage = _init_storage()
  File "/usr/local/lib/python3.5/site-packages/timetra.diary-0.2.0-py3.5.egg/timetra/diary/app.py", line 53, in _init_storage
    with open(CONF_FILE) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'conf.yaml'
```

**Comment by neithere** [comment]
Hi Hörmet,

Thanks for the interest! You are probably the first person besides myself to run it, so no wonder that there was a problem. :-)

Sorry for the lack of documentation. Let's try to write it here, then I'll be able to update the README later.

The config file is expected to sit in the path specified in the `TIMETRA_DIARY_CONFIG` env var. So you can either export this e.g. in your `.bashrc`, or run the binary like this:
```bash
TIMETRA_DIARY_CONFIG=~/.config/timetra-diary.yaml
```

Of course the config should also exist. Minimal example:
```yaml
backend:
  data_dir: /home/jdoe/.local/share/timetra-diary/
```

Then try adding some fact:
```bash
$ timetra-diary add -30 work/myproject added feature X -t at-home
Add work/myproject as a new kind of activity? (y/n) y
Added 2016-07-27 17:35 +30m to /home/jdoe/.local/share/timetra-diary/2016/07/27.yaml
```

Now look at the data dir that you have specified in the config:
```bash
$ tree /home/jdoe/.local/share/timetra-diary/
/home/jdoe/.local/share/timetra-diary/
├── 2016
│   ├── 07
│   │   └── 27.yaml
```

What has been logged for today? Let's see:
```bash
$ timetra-diary today
2016-07-27 17:35-18:04 work/myproject 30m added feature X 
```

How is it stored? Look at `/home/jdoe/.local/share/timetra-diary/2016/07/27.yaml`:
```yaml
- activity: work/myproject
  since: 2016-07-27 17:35:00
  until: 2016-07-27 18:04:50.721670
  description: added feature X
  tags:
  - at-home
```

Naturally, you can edit this file with your favourite editor.

The **directory tree with YAML files *is* the database**. Each newly added/changed file is parsed from YAML to native Python data structures and cached into a fast k/v store (see [caching.Cache](https://github.com/neithere/timetra.diary/blob/master/timetra/diary/caching.py#L16)). The caching occurs during search operations, e.g. `timetra-diary today`, `timetra-diary yesterday` or a more generic `timetra-diary find`. If the cache gets corrupted, it usually gets automatically rebuilt.

Finding activities:
```bash
$ timetra-diary find -a work/myproject -n feat
2016-07-27 17:35-18:04 work/myproject 30m added feature X
```

In order to prevent typos and offer autocompletion, Timetra Diary keeps known **activity names** as a controlled dictionary. When you enter an unknown activity name, it asks you whether you want to add it; if it could find some matches, it offers them as choices; if there was just one match (e.g. you entered `myp` and it matched `work/myproject`), it asks you if you meant the known one.

There are some built-in **reports** on activities; `drift` and `weekly` are especially useful for sleep and sport/workout tracking. See `timetra-diary help report drift`.

Hint:
```bash
echo 'alias t="timetra-diary"'  >> ~/.bashrc
echo 'alias ta="timetra-diary add"'  >> ~/.bashrc
```

Any feedback is highly appreciated.

Cheers,
Andy

**Comment by neithere** [comment]
P.S.: there's no documentation on timespec syntax either, so meanwhile unit tests can be used as such: https://github.com/neithere/timetra.diary/blob/master/tests/utils_test.py#L14

There's one edge case: when you say something like `-15` (started 15 minutes ago), it's fine; however, `-15..-5` (i.e. started 15 minutes ago, ended 5 minutes ago) is interpreted by CLI the argument parser as an _argument name_, so it will fail. A workaround is to prefix the string with a space and quote this whole thing: `' -5..-5'`. The argument parser will not see a dash in the beginning of the string any more and will interpret it as a positional argument; Timetra Diary will in turn trim the value. It's a hack but it's very rarely needed, so I don't think we should rethink the whole syntax.
